using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CollisionB;

[Generator(LanguageNames.CSharp)]
public sealed class CollisionGeneratorB : IIncrementalGenerator
{
    // Intentionally identical HintName to CollisionA — proves HintName is not a cross-generator key.
    public const string SharedHintName = "SharedHint.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(SharedHintName, SourceText.From(
                """
                // <auto-generated/>
                namespace CollisionHost.Generated;

                public static class FromB
                {
                    public static string Who => "CollisionB";
                }
                """,
                Encoding.UTF8));
        });
    }
}
