<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>S2.Bench</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\S2.Core\S2.Core.csproj" />
  </ItemGroup>
</Project>
