using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CustomGenerator;

/// <summary>Emits the shared HintName used by <see cref="CollisionGeneratorB"/>.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class CollisionGeneratorA : IIncrementalGenerator
{
    public const string SharedHintName = "SharedHint.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(SharedHintName, SourceText.From(
                """
                // <auto-generated/>
                namespace GeneratorHost.Collision;

                public static class FromA
                {
                    public static string Tag => "A";
                }
                """,
                Encoding.UTF8));
        });
    }
}
