using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CustomGenerator;

/// <summary>Emits the same HintName as <see cref="CollisionGeneratorA"/> with different content.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class CollisionGeneratorB : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(CollisionGeneratorA.SharedHintName, SourceText.From(
                """
                // <auto-generated/>
                namespace GeneratorHost.Collision;

                public static class FromB
                {
                    public static string Tag => "B";
                }
                """,
                Encoding.UTF8));
        });
    }
}
