using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CustomGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class MarkerGenerator : IIncrementalGenerator
{
    public const string HintName = "CustomGenerator.Marker.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(HintName, SourceText.From(
                """
                // <auto-generated/>
                namespace SampleApp.Generated;

                public static class CustomMarker
                {
                    public static string Who => "CustomGenerator.MarkerGenerator";
                }
                """,
                Encoding.UTF8));
        });
    }
}
