using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Avalonia.NameGenerator;

/// <summary>
/// Fixture stand-in for Avalonia XAML NameGenerator — emits x:Name fields on SampleApp.MainWindow.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class NameGenerator : IIncrementalGenerator
{
    public const string HintName = "SampleApp.MainWindow.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(HintName, SourceText.From(
                """
                // <auto-generated/>
                namespace SampleApp;

                public partial class MainWindow
                {
                    internal object TitleText;
                }
                """,
                Encoding.UTF8));
        });
    }
}
