using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CustomGenerator;

/// <summary>
/// Augments handwritten <c>GeneratorHost.PartialThing</c> with a generated member for attribution tests.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PartialAugmentGenerator : IIncrementalGenerator
{
    public const string HintName = "CustomGenerator.PartialThing.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(HintName, SourceText.From(
                """
                // <auto-generated/>
                namespace GeneratorHost;

                public partial class PartialThing
                {
                    public int GeneratedValue => 99;
                }
                """,
                Encoding.UTF8));
        });
    }
}
