using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CustomGenerator;

[Generator(LanguageNames.VisualBasic)]
public sealed class VbMarkerGenerator : IIncrementalGenerator
{
    public const string HintName = "CustomGenerator.VbMarker.g.vb";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(HintName, SourceText.From(
                """
                ' <auto-generated/>
                Namespace SampleApp.Generated
                    Public Class VbMarker
                        Public Shared Function Who() As String
                            Return "CustomGenerator.VbMarkerGenerator"
                        End Function
                    End Class
                End Namespace
                """,
                Encoding.UTF8));
        });
    }
}
