using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CustomGenerator;

[Generator(LanguageNames.VisualBasic)]
public sealed class VbPartialAugmentGenerator : IIncrementalGenerator
{
    public const string HintName = "CustomGenerator.VbPartialThing.g.vb";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(HintName, SourceText.From(
                """
                ' <auto-generated/>
                Namespace GeneratorHost
                    Partial Public Class VbPartialThing
                        Public Function GeneratedValue() As Integer
                            Return 99
                        End Function
                    End Class
                End Namespace
                """,
                Encoding.UTF8));
        });
    }
}
