using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CollisionA;

[Generator(LanguageNames.CSharp)]
public sealed class CollisionGeneratorA : IIncrementalGenerator
{
    public const string SharedHintName = "SharedHint.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(SharedHintName, SourceText.From(
                """
                // <auto-generated/>
                namespace CollisionHost.Generated;

                public static class FromA
                {
                    public static string Who => "CollisionA";
                }
                """,
                Encoding.UTF8));
        });
    }
}
